feat(initialize): Add skeleton files
mamoonraja/vcap-services-python pull request #1
Opened 2018-07-27 21:10 UTC by mamoonraja

2018-08-01 12:43 UTC, germanattanasio commented on .travis.yml
> +  - "3.4"
2.7 should be added

2018-08-01 12:48 UTC, germanattanasio requested changes
This is great progress.
Todo
- [x] add a linter 
- [x] get 100% code coverage
- [x] Support all the features from the node.js package

2018-08-01 12:48 UTC, germanattanasio commented on setup.py
> +      packages=['vcap_services'],
`vcap-services`not `vcap_services`

2018-08-01 12:48 UTC, germanattanasio commented on test/test_vcap-services.py
> +from vcap_services import parse_credentials, load_from_vcap_services, get_creds_for_starter
`test/test_parse_credentials.py`

2018-08-01 12:48 UTC, germanattanasio commented on vcap_services/index.py
> +def get_creds_for_starter(service_label, credentials_from_local_config=None):
`get credentials from file`

2018-08-01 12:48 UTC, germanattanasio commented on vcap_services/index.py
> +    key = "watson_" + service_label + "_"
do we use single quote or double quote?

2018-08-01 12:50 UTC, germanattanasio commented
You need to write tests for when things are None and to separate them in different tests rather than listing them all in one

2018-08-02 21:23 UTC, germanattanasio requested changes

2018-08-02 21:23 UTC, germanattanasio commented on setup.py
> +    from pypandoc import convert
you are not installing `pypandoc`.

2018-08-02 21:23 UTC, germanattanasio commented on setup.py
> +      description='Client library to use VCAP SERVICES',
Find a better description

2018-08-03 15:32 UTC, mamoonraja commented on setup.py
> +    from pypandoc import convert
added to `requirements.txt`

2018-08-03 16:53 UTC, germanattanasio approved these changes

2018-08-03 20:11 UTC, merged

2018-08-03 20:54 UTC, mamoonraja commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/mamoonraja/vcap-services-python/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: